SELECT MEMBER_ID, MEMBER_NAME, GENDER, SUBSTRING(DATE_OF_BIRTH, 1, 10) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' AND SUBSTRING(DATE_OF_BIRTH, 6, 2) = '03' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID